{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "krop-controller.fullname" . }}
  labels:
    {{- include "krop-controller.labels" . | nindent 4 }}
{{- $role := .Files.Get "files/role.yaml" | fromYaml }}
rules:
  {{- $role.rules | toYaml | nindent 2 }}
{{- end }}
