name: Codegen Check
permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - id: go-version
        uses: opendefensecloud/dev-kit/.github/actions/get-go-version@8cb6197cd7a2f93bc5cf12c689e48df615f1dbde # v1.0.14
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version: ${{ steps.go-version.outputs.version }}
      - name: Run codegen
        run: |
          make generate manifests
      - name: Check for changes
        uses: opendefensecloud/dev-kit/.github/actions/diff-check@8cb6197cd7a2f93bc5cf12c689e48df615f1dbde # v1.0.14
